////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.

NOTE: For help with the syntax of this file, see:
http://maven.apache.org/guides/mini/guide-apt-format.html
////

= Archiva Components

Archiva Components bundles different independent component modules, that are used by Archiva and Redback, and are free
to use by other projects.

Currently the component project contains the following components:

- link:archiva-components-expression-evaluator/index.html[expression-evaluatior]
- link:archiva-components-graph/index.html[graph]
- link:archiva-components-spring-apacheds/index.html[spring-apacheds]
- link:archiva-components-spring-cache/index.html[spring-cache]
- link:archiva-components-spring-registry/index.html[spring-registry]
- link:archiva-components-spring-taskqueue/index.html[spring-taskqueue]
